import './globals.css'
import { MonaSans } from "./fontLoader"

export const metadata = {
  title: "Safe With Muhinat",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={MonaSans.className}>
        {children}
      </body>
    </html>
  );
}
